trailingComma: "es5"
tabWidth: 4
semi: false
singleQuote: true
plugins: [
  "prettier-plugin-tailwindcss"
]
tailwindStylesheet: "./resources/css/app.css"
tailwindPreserveWhitespace: false
# tailwindConfig: "./styles/tailwind.config.js"
